version: "2.4"

services:
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src
      - /usr/src/node_modules
    networks: 
      giothnet:
        ipv4_address: 172.28.1.2

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src
      - /usr/src/node_modules
    networks:
      giothnet:
        ipv4_address: 172.28.1.3

  db:
    image: mongo
    networks: 
      giothnet:
        ipv4_address: 172.28.1.4
    volumes:
      - dbdata:/data/db

networks:
  giothnet:
    ipam:
      driver: default
      config: 
        - subnet: 172.28.1.0/16
          gateway: 172.28.1.1

volumes: 
  dbdata:
    external: true
